name: Build and Run Java Docker

# Khi nào workflow chạy
on:
  push:
    branches:
      - main   # hoặc branch bạn muốn
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t myjavaapp:latest .

      # 4️⃣ Run container (optional)
      - name: Run Docker container
        run: |
          docker run --rm myjavaapp:latest
